config/routes.rb
Hackfsm::Application.routes.draw do

  root 'home#timeline'

  get 'timeline' => 'home#timeline'
  get 'details/:id' => 'timeline#show', id: /.*/, as: :details

  get 'search' => 'timeline#search'
  post 'search' => 'timeline#search_post'

  resources :people, only: [:index, :show]

end

app/views/layouts/_header.html.erb
<div id="header" class="container-fluid">
  <div class="row">
    <div class="col-md-2 col-md-offset-2"> 
      <%= link_to root_path, class: "logo" do %>
        <%= image_tag "logo.png", alt: "Free Speech Movement" %>
      <% end %>
    </div>
    <div class="col-md-6">
      <ul>
        <li><%= link_to "People", people_path %></li>
        <li><%= link_to "Events", timeline_path %></li>
        <li><%= link_to "Search", search_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>The Free Speech Movement Archive - <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/timeline.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>The Free Speech Movement Archive - <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body id="timeline-body" data-spy="scroll" data-target="#timeline-select"
    data-offset="100">

<%= render "layouts/header" %>
<%= yield(:sidebar) %>
<%= yield %>

</body>
</html>